#!/bin/bash
# ask tools pre-push hook

profile=$(tr -d '\n' < ./.ask/ask-states.json | tr -d ' ' | sed -n 's/.*"profiles":{"\([^{]*\)":.*/\1/p' | sed 's/".*//')
skillId=$(tr -d '\n' < ./.ask/ask-states.json | tr -d ' ' | sed -n 's/.*"profiles":{"[^{]*":{"skillId":"\(.*\)".*/\1/p' | sed 's/".*//')
locale=$(tr -d '\n' < ./skill-package/skill.json | tr -d ' ' | sed -n 's/.*"locales":{"\([^{]*\)":.*/\1/p' | sed 's/".*//' | sed -n 's/-/_/p' )
currentBranch=$(git rev-parse --abbrev-ref HEAD)
customRepo=$2

bash ~/.ask/scripts/ask-pre-push "${profile}" "${skillId}" "${locale}" "${currentBranch}" "${customRepo}"